version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    build: ./api
    ports:
      - '2222:2222'
    volumes:
      - ./api:/app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "c0759048345d5dc4bc7348a131716c1e0acca53e"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    volumes:
      - mongodb_data:/data/db
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: "c0759048345d5dc4bc7348a131716c1e0acca53e"
    depends_on:
      - mongo
  
volumes:
  mongodb_data: